[2025-05-22T16:02:17.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T15:30:00+00:00 [queued]>
[2025-05-22T16:02:17.175+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T15:30:00+00:00 [queued]>
[2025-05-22T16:02:17.177+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2025-05-22T16:02:17.191+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Transform_Data> on 2025-05-22 15:30:00+00:00
[2025-05-22T16:02:17.199+0000] {standard_task_runner.py:57} INFO - Started process 1478 to run task
[2025-05-22T16:02:17.202+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Transform_Data', 'scheduled__2025-05-22T15:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmp_a27judl']
[2025-05-22T16:02:17.205+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask Transform_Data
[2025-05-22T16:02:17.269+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T15:30:00+00:00 [running]> on host 1f18d06af689
[2025-05-22T16:02:17.358+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Transform_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T15:30:00+00:00'
[2025-05-22T16:02:17.360+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T16:02:17.362+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Transform_Data.py']
[2025-05-22T16:02:17.376+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T16:02:18.922+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T16:02:18.922+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T16:02:18.924+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T16:02:18.926+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T16:02:18.927+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T16:02:19.095+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T16:02:19.180+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T16:02:19.182+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T16:02:19.185+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T16:02:19.186+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-b7de1ede-2303-4b1b-9823-0135178f4b65;1.0
[2025-05-22T16:02:19.187+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:02:19.304+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T16:02:19.332+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T16:02:19.352+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 160ms :: artifacts dl 6ms
[2025-05-22T16:02:19.353+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T16:02:19.353+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T16:02:19.354+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T16:02:19.354+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:02:19.354+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T16:02:19.355+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T16:02:19.356+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:02:19.357+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T16:02:19.358+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:02:19.359+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-b7de1ede-2303-4b1b-9823-0135178f4b65
[2025-05-22T16:02:19.360+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:02:19.365+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/6ms)
[2025-05-22T16:02:19.554+0000] {subprocess.py:93} INFO - 25/05/22 16:02:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T16:02:19.813+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T16:02:19.814+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T16:02:19.814+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T16:02:27.762+0000] {subprocess.py:93} INFO - [Stage 1:>                                                        (0 + 13) / 13][Stage 1:====>                                                    (1 + 12) / 13]                                                                                25/05/22 16:02:27 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2025-05-22T16:02:39.928+0000] {subprocess.py:93} INFO - [Stage 2:====>                                                    (1 + 12) / 13]                                                                                [Stage 4:>                (0 + 13) / 13][Stage 7:>                 (0 + 7) / 13][Stage 4:=>               (1 + 12) / 13][Stage 7:>                 (0 + 8) / 13][Stage 4:==>              (2 + 11) / 13][Stage 7:>                 (0 + 9) / 13][Stage 4:=========>        (7 + 6) / 13][Stage 7:>                (0 + 13) / 13][Stage 7:========>                                                (2 + 11) / 13][Stage 7:========================================>                 (9 + 4) / 13][Stage 5:==========>   (154 + 18) / 200][Stage 7:=============>   (10 + 3) / 13][Stage 8:>                                                          (0 + 1) / 1]                                                                                [Stage 15:>                                                         (0 + 1) / 1]                                                                                Saved: /opt/***/data/Clean_Crash_Data.csv
[2025-05-22T16:02:39.930+0000] {subprocess.py:93} INFO - Saved: /opt/***/data/Clean_Crash_Date_Data.csv
[2025-05-22T16:02:39.931+0000] {subprocess.py:93} INFO - Saved: /opt/***/data/Clean_Road_Data.csv
[2025-05-22T16:02:40.511+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-22T16:02:40.549+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Scheduler_Traffict_Accident, task_id=Transform_Data, execution_date=20250522T153000, start_date=20250522T160217, end_date=20250522T160240
[2025-05-22T16:02:40.598+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-22T16:02:40.637+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
