[2025-05-14T16:45:01.414+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T16:40:00+00:00 [queued]>
[2025-05-14T16:45:01.426+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T16:40:00+00:00 [queued]>
[2025-05-14T16:45:01.427+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T16:45:01.428+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-14T16:45:01.429+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T16:45:01.443+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Extract_Data> on 2025-05-14 16:40:00+00:00
[2025-05-14T16:45:01.450+0000] {standard_task_runner.py:52} INFO - Started process 36570 to run task
[2025-05-14T16:45:01.453+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Sales_Performance_ETL', 'Extract_Data', 'scheduled__2025-05-14T16:40:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Hisham_Audiputra_Suharto_DAG.py', '--cfg-path', '/tmp/tmp68o6mw8r', '--error-file', '/tmp/tmpkh7tf91p']
[2025-05-14T16:45:01.455+0000] {standard_task_runner.py:80} INFO - Job 159: Subtask Extract_Data
[2025-05-14T16:45:01.539+0000] {task_command.py:371} INFO - Running <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T16:40:00+00:00 [running]> on host 2ca7303636ab
[2025-05-14T16:45:01.632+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Sales_Performance_ETL
AIRFLOW_CTX_TASK_ID=Extract_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T16:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T16:40:00+00:00
[2025-05-14T16:45:01.633+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-14T16:45:01.635+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Data.py']
[2025-05-14T16:45:01.649+0000] {subprocess.py:85} INFO - Output:
[2025-05-14T16:45:02.476+0000] {subprocess.py:92} INFO - Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.12)
[2025-05-14T16:45:02.507+0000] {subprocess.py:92} INFO - Path to dataset files: /home/***/.cache/kagglehub/datasets/zahidmughal2343/supplement-sales-data/versions/1
[2025-05-14T16:45:02.508+0000] {subprocess.py:92} INFO - Path to dataset files: /home/***/.cache/kagglehub/datasets/zahidmughal2343/supplement-sales-data/versions/1
[2025-05-14T16:45:02.534+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2025-05-14T16:45:02.566+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=Sales_Performance_ETL, task_id=Extract_Data, execution_date=20250514T164000, start_date=20250514T164501, end_date=20250514T164502
[2025-05-14T16:45:02.593+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-05-14T16:45:02.644+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
