[2025-05-14T14:10:01.282+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T14:05:00+00:00 [queued]>
[2025-05-14T14:10:01.295+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T14:05:00+00:00 [queued]>
[2025-05-14T14:10:01.296+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T14:10:01.299+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-14T14:10:01.299+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T14:10:01.315+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Extract_Data> on 2025-05-14 14:05:00+00:00
[2025-05-14T14:10:01.323+0000] {standard_task_runner.py:52} INFO - Started process 15287 to run task
[2025-05-14T14:10:01.326+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Sales_Performance_ETL', 'Extract_Data', 'scheduled__2025-05-14T14:05:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Hisham_Audiputra_Suharto_DAG.py', '--cfg-path', '/tmp/tmpr8p8veb6', '--error-file', '/tmp/tmp2nhmhq9j']
[2025-05-14T14:10:01.330+0000] {standard_task_runner.py:80} INFO - Job 66: Subtask Extract_Data
[2025-05-14T14:10:01.414+0000] {task_command.py:371} INFO - Running <TaskInstance: Sales_Performance_ETL.Extract_Data scheduled__2025-05-14T14:05:00+00:00 [running]> on host 2ca7303636ab
[2025-05-14T14:10:01.491+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Sales_Performance_ETL
AIRFLOW_CTX_TASK_ID=Extract_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T14:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T14:05:00+00:00
[2025-05-14T14:10:01.493+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-14T14:10:01.495+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Data.py']
[2025-05-14T14:10:01.504+0000] {subprocess.py:85} INFO - Output:
[2025-05-14T14:10:02.310+0000] {subprocess.py:92} INFO - Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.12)
[2025-05-14T14:10:02.337+0000] {subprocess.py:92} INFO - Path to dataset files: /home/***/.cache/kagglehub/datasets/zahidmughal2343/supplement-sales-data/versions/1
[2025-05-14T14:10:02.337+0000] {subprocess.py:92} INFO - Path to dataset files: /home/***/.cache/kagglehub/datasets/zahidmughal2343/supplement-sales-data/versions/1
[2025-05-14T14:10:02.360+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2025-05-14T14:10:02.402+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=Sales_Performance_ETL, task_id=Extract_Data, execution_date=20250514T140500, start_date=20250514T141001, end_date=20250514T141002
[2025-05-14T14:10:02.427+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-05-14T14:10:02.500+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
