[2025-05-14T13:40:13.986+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:35:00+00:00 [queued]>
[2025-05-14T13:40:13.997+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:35:00+00:00 [queued]>
[2025-05-14T13:40:13.999+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T13:40:14.004+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-14T13:40:14.005+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T13:40:14.023+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-14 13:35:00+00:00
[2025-05-14T13:40:14.031+0000] {standard_task_runner.py:52} INFO - Started process 11477 to run task
[2025-05-14T13:40:14.035+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Sales_Performance_ETL', 'Load_Data', 'scheduled__2025-05-14T13:35:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Hisham_Audiputra_Suharto_DAG.py', '--cfg-path', '/tmp/tmp5rz57ik8', '--error-file', '/tmp/tmpokumfuw9']
[2025-05-14T13:40:14.038+0000] {standard_task_runner.py:80} INFO - Job 50: Subtask Load_Data
[2025-05-14T13:40:14.107+0000] {task_command.py:371} INFO - Running <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:35:00+00:00 [running]> on host 2ca7303636ab
[2025-05-14T13:40:14.193+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Sales_Performance_ETL
AIRFLOW_CTX_TASK_ID=Load_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T13:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T13:35:00+00:00
[2025-05-14T13:40:14.195+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-14T13:40:14.196+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-14T13:40:14.206+0000] {subprocess.py:85} INFO - Output:
[2025-05-14T13:40:16.018+0000] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-14T13:40:16.018+0000] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-14T13:40:16.019+0000] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-14T13:40:16.019+0000] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-14T13:40:16.020+0000] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-14T13:40:16.154+0000] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-14T13:40:16.231+0000] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-14T13:40:16.232+0000] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-14T13:40:16.235+0000] {subprocess.py:92} INFO - org.postgresql#postgresql added as a dependency
[2025-05-14T13:40:16.236+0000] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-17f1d62c-b796-44b3-a87c-726b610496ee;1.0
[2025-05-14T13:40:16.237+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-14T13:40:16.318+0000] {subprocess.py:92} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-14T13:40:16.339+0000] {subprocess.py:92} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-14T13:40:16.354+0000] {subprocess.py:92} INFO - :: resolution report :: resolve 113ms :: artifacts dl 5ms
[2025-05-14T13:40:16.355+0000] {subprocess.py:92} INFO - 	:: modules in use:
[2025-05-14T13:40:16.356+0000] {subprocess.py:92} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-14T13:40:16.357+0000] {subprocess.py:92} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-14T13:40:16.357+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:40:16.358+0000] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-14T13:40:16.359+0000] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-14T13:40:16.360+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:40:16.360+0000] {subprocess.py:92} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-14T13:40:16.361+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:40:16.362+0000] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-17f1d62c-b796-44b3-a87c-726b610496ee
[2025-05-14T13:40:16.362+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-14T13:40:16.363+0000] {subprocess.py:92} INFO - 	0 artifacts copied, 2 already retrieved (0kB/5ms)
[2025-05-14T13:40:16.535+0000] {subprocess.py:92} INFO - 25/05/14 13:40:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-14T13:40:16.748+0000] {subprocess.py:92} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-14T13:40:16.749+0000] {subprocess.py:92} INFO - Setting default log level to "WARN".
[2025-05-14T13:40:16.750+0000] {subprocess.py:92} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-14T13:40:27.838+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2025-05-14T13:40:27.899+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=Sales_Performance_ETL, task_id=Load_Data, execution_date=20250514T133500, start_date=20250514T134013, end_date=20250514T134027
[2025-05-14T13:40:27.958+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-05-14T13:40:28.001+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
