[2025-05-14T13:55:13.101+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:50:00+00:00 [queued]>
[2025-05-14T13:55:13.123+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:50:00+00:00 [queued]>
[2025-05-14T13:55:13.124+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T13:55:13.130+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-14T13:55:13.131+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T13:55:13.161+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-14 13:50:00+00:00
[2025-05-14T13:55:13.169+0000] {standard_task_runner.py:52} INFO - Started process 13517 to run task
[2025-05-14T13:55:13.174+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Sales_Performance_ETL', 'Load_Data', 'scheduled__2025-05-14T13:50:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Hisham_Audiputra_Suharto_DAG.py', '--cfg-path', '/tmp/tmpzcuirqxa', '--error-file', '/tmp/tmp1oh8fjd8']
[2025-05-14T13:55:13.177+0000] {standard_task_runner.py:80} INFO - Job 59: Subtask Load_Data
[2025-05-14T13:55:13.268+0000] {task_command.py:371} INFO - Running <TaskInstance: Sales_Performance_ETL.Load_Data scheduled__2025-05-14T13:50:00+00:00 [running]> on host 2ca7303636ab
[2025-05-14T13:55:13.364+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Sales_Performance_ETL
AIRFLOW_CTX_TASK_ID=Load_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T13:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T13:50:00+00:00
[2025-05-14T13:55:13.366+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-14T13:55:13.368+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-14T13:55:13.379+0000] {subprocess.py:85} INFO - Output:
[2025-05-14T13:55:15.130+0000] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-14T13:55:15.131+0000] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-14T13:55:15.131+0000] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-14T13:55:15.132+0000] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-14T13:55:15.132+0000] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-14T13:55:15.259+0000] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-14T13:55:15.321+0000] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-14T13:55:15.322+0000] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-14T13:55:15.325+0000] {subprocess.py:92} INFO - org.postgresql#postgresql added as a dependency
[2025-05-14T13:55:15.326+0000] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a900997a-ca56-4a58-91dc-7972d3423d86;1.0
[2025-05-14T13:55:15.327+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-14T13:55:15.417+0000] {subprocess.py:92} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-14T13:55:15.441+0000] {subprocess.py:92} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-14T13:55:15.457+0000] {subprocess.py:92} INFO - :: resolution report :: resolve 126ms :: artifacts dl 5ms
[2025-05-14T13:55:15.458+0000] {subprocess.py:92} INFO - 	:: modules in use:
[2025-05-14T13:55:15.458+0000] {subprocess.py:92} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-14T13:55:15.459+0000] {subprocess.py:92} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-14T13:55:15.460+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:55:15.460+0000] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-14T13:55:15.461+0000] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-14T13:55:15.461+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:55:15.462+0000] {subprocess.py:92} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-14T13:55:15.463+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-14T13:55:15.463+0000] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-a900997a-ca56-4a58-91dc-7972d3423d86
[2025-05-14T13:55:15.464+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-14T13:55:15.465+0000] {subprocess.py:92} INFO - 	0 artifacts copied, 2 already retrieved (0kB/4ms)
[2025-05-14T13:55:15.629+0000] {subprocess.py:92} INFO - 25/05/14 13:55:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-14T13:55:15.832+0000] {subprocess.py:92} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-14T13:55:15.833+0000] {subprocess.py:92} INFO - Setting default log level to "WARN".
[2025-05-14T13:55:15.834+0000] {subprocess.py:92} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-14T13:55:26.908+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2025-05-14T13:55:26.947+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=Sales_Performance_ETL, task_id=Load_Data, execution_date=20250514T135000, start_date=20250514T135513, end_date=20250514T135526
[2025-05-14T13:55:26.999+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-05-14T13:55:27.039+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
